DROP TABLE IF EXISTS `cdr`;
DROP TABLE IF EXISTS `cmr`;

CREATE TABLE `cdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cdrRecordType` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callManagerId` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callId` int(11) NOT NULL DEFAULT '0',
  `origLegCallIdentifier` int(11) NOT NULL DEFAULT '0',
  `dateTimeOrigination` int(11) NOT NULL DEFAULT '0',
  `origNodeId` int(11) NOT NULL DEFAULT '0',
  `origSpan` int(11) NOT NULL DEFAULT '0',
  `origIpAddr` int(11) unsigned NOT NULL DEFAULT '0',
  `callingPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `callingPartyUnicodeLoginUserID` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `origCause_location` int(11) NOT NULL DEFAULT '0',
  `origCause_value` int(11) NOT NULL DEFAULT '0',
  `origPrecedenceLevel` int(11) NOT NULL DEFAULT '0',
  `origMediaTransportAddress_IP` int(11) unsigned NOT NULL DEFAULT '0',
  `origMediaTransportAddress_Port` int(11) NOT NULL DEFAULT '0',
  `origMediaCap_payloadCapability` int(11) NOT NULL DEFAULT '0',
  `origMediaCap_maxFramesPerPacket` int(11) NOT NULL DEFAULT '0',
  `origMediaCap_g723BitRate` int(11) NOT NULL DEFAULT '0',
  `origVideoCap_Codec` int(11) NOT NULL DEFAULT '0',
  `origVideoCap_Bandwidth` int(11) NOT NULL DEFAULT '0',
  `origVideoCap_Resolution` int(11) NOT NULL DEFAULT '0',
  `origVideoTransportAddress_IP` int(11) unsigned NOT NULL DEFAULT '0',
  `origVideoTransportAddress_Port` int(11) NOT NULL DEFAULT '0',
  `origRSVPAudioStat` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `origRSVPVideoStat` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `destLegIdentifier` int(11) NOT NULL DEFAULT '0',
  `destNodeId` int(11) NOT NULL DEFAULT '0',
  `destSpan` int(11) NOT NULL DEFAULT '0',
  `destIpAddr` int(11) unsigned NOT NULL DEFAULT '0',
  `originalCalledPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `finalCalledPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `finalCalledPartyUnicodeLoginUserID` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `destCause_location` int(11) NOT NULL DEFAULT '0',
  `destCause_value` int(11) NOT NULL DEFAULT '0',
  `destPrecedenceLevel` int(11) NOT NULL DEFAULT '0',
  `destMediaTransportAddress_IP` int(11) unsigned NOT NULL DEFAULT '0',
  `destMediaTransportAddress_Port` int(11) NOT NULL DEFAULT '0',
  `destMediaCap_payloadCapability` int(11) NOT NULL DEFAULT '0',
  `destMediaCap_maxFramesPerPacket` int(11) NOT NULL DEFAULT '0',
  `destMediaCap_g723BitRate` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Codec` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Bandwidth` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Resolution` int(11) NOT NULL DEFAULT '0',
  `destVideoTransportAddress_IP` int(11) unsigned NOT NULL DEFAULT '0',
  `destVideoTransportAddress_Port` int(11) NOT NULL DEFAULT '0',
  `destRSVPAudioStat` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `destRSVPVideoStat` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `dateTimeConnect` int(11) NOT NULL DEFAULT '0',
  `dateTimeDisconnect` int(11) NOT NULL DEFAULT '0',
  `lastRedirectDn` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `pkid` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `originalCalledPartyNumberPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `callingPartyNumberPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `finalCalledPartyNumberPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `lastRedirectDnPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `duration` int(11) NOT NULL DEFAULT '0',
  `origDeviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `destDeviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `origCallTerminationOnBehalfOf` int(11) NOT NULL DEFAULT '0',
  `destCallTerminationOnBehalfOf` int(11) NOT NULL DEFAULT '0',
  `origCalledPartyRedirectOnBehalfOf` int(11) NOT NULL DEFAULT '0',
  `lastRedirectRedirectOnBehalfOf` int(11) NOT NULL DEFAULT '0',
  `origCalledPartyRedirectReason` int(11) NOT NULL DEFAULT '0',
  `lastRedirectRedirectReason` int(11) NOT NULL DEFAULT '0',
  `destConversationId` int(11) NOT NULL DEFAULT '0',
  `globalCallId_ClusterID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `joinOnBehalfOf` int(11) NOT NULL DEFAULT '0',
  `comment` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `authCodeDescription` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `authorizationLevel` int(11) NOT NULL DEFAULT '0',
  `clientMatterCode` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `origDTMFMethod` int(11) NOT NULL DEFAULT '0',
  `destDTMFMethod` int(11) NOT NULL DEFAULT '0',
  `callSecuredStatus` int(11) NOT NULL DEFAULT '0',
  `origConversationId` int(11) NOT NULL DEFAULT '0',
  `origMediaCap_Bandwidth` int(11) NOT NULL DEFAULT '0',
  `destMediaCap_Bandwidth` int(11) NOT NULL DEFAULT '0',
  `authorizationCodeValue` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `outpulsedCallingPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `outpulsedCalledPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `origIpv4v6Addr` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `destIpv4v6Addr` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `origVideoCap_Codec_Channel2` int(11) NOT NULL DEFAULT '0',
  `origVideoCap_Bandwidth_Channel2` int(11) NOT NULL DEFAULT '0',
  `origVideoCap_Resolution_Channel2` int(11) NOT NULL DEFAULT '0',
  `origVideoTransportAddress_IP_Channel2` int(11) unsigned NOT NULL DEFAULT '0',
  `origVideoTransportAddress_Port_Channel2` int(11) NOT NULL DEFAULT '0',
  `origVideoChannel_Role_Channel2` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Codec_Channel2` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Bandwidth_Channel2` int(11) NOT NULL DEFAULT '0',
  `destVideoCap_Resolution_Channel2` int(11) NOT NULL DEFAULT '0',
  `destVideoTransportAddress_IP_Channel2` int(11) unsigned NOT NULL DEFAULT '0',
  `destVideoTransportAddress_Port_Channel2` int(11) NOT NULL DEFAULT '0',
  `destVideoChannel_Role_Channel2` int(11) NOT NULL DEFAULT '0',
  `IncomingProtocolID` int(11) NOT NULL DEFAULT '0',
  `IncomingProtocolCallRef` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `OutgoingProtocolID` int(11) NOT NULL DEFAULT '0',
  `OutgoingProtocolCallRef` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `currentRoutingReason` int(11) NOT NULL DEFAULT '0',
  `origRoutingReason` int(11) NOT NULL DEFAULT '0',
  `lastRedirectingRoutingReason` int(11) NOT NULL DEFAULT '0',
  `huntPilotPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `huntPilotDN` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `calledPartyPatternUsage` int(11) NOT NULL DEFAULT '0',
  `IncomingICID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `IncomingOrigIOI` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `IncomingTermIOI` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `OutgoingICID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `OutgoingOrigIOI` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `OutgoingTermIOI` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `outpulsedOriginalCalledPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `outpulsedLastRedirectingNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `wasCallQueued` int(11) NOT NULL DEFAULT '0',
  `totalWaitTimeInQueue` int(11) NOT NULL DEFAULT '0',
  `callingPartyNumber_uri` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `originalCalledPartyNumber_uri` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `finalCalledPartyNumber_uri` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lastRedirectDn_uri` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `mobileCallingPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `finalMobileCalledPartyNumber` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `origMobileDeviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `destMobileDeviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `origMobileCallDuration` int(11) NOT NULL DEFAULT '0',
  `destMobileCallDuration` int(11) NOT NULL DEFAULT '0',
  `mobileCallType` int(11) NOT NULL DEFAULT '0',
  `originalCalledPartyPattern` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `finalCalledPartyPattern` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `lastRedirectingPartyPattern` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `huntPilotPattern` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=403051 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `cmr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cdrRecordType` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callManagerId` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callId` int(11) NOT NULL DEFAULT '0',
  `nodeId` int(11) NOT NULL DEFAULT '0',
  `directoryNum` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `callIdentifier` int(11) NOT NULL DEFAULT '0',
  `dateTimeStamp` int(11) NOT NULL DEFAULT '0',
  `numberPacketsSent` int(11) NOT NULL DEFAULT '0',
  `numberOctetsSent` int(11) NOT NULL DEFAULT '0',
  `numberPacketsReceived` int(11) NOT NULL DEFAULT '0',
  `numberOctetsReceived` int(11) NOT NULL DEFAULT '0',
  `numberPacketsLost` int(11) NOT NULL DEFAULT '0',
  `jitter` int(11) NOT NULL DEFAULT '0',
  `latency` int(11) NOT NULL DEFAULT '0',
  `pkid` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `directoryNumPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `globalCallId_ClusterID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `deviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `varVQMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `duration` int(11) NOT NULL DEFAULT '0',
  `videoContentType` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `videoDuration` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsSent` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsSent` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsReceived` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsReceived` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsLost` int(11) NOT NULL DEFAULT '0',
  `videoAverageJitter` int(11) NOT NULL DEFAULT '0',
  `videoRoundTripTime` int(11) NOT NULL DEFAULT '0',
  `videoOneWayDelay` int(11) NOT NULL DEFAULT '0',
  `videoReceptionMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoTransmissionMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoContentType_channel2` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `videoDuration_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsSent_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsSent_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsReceived_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsReceived_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsLost_channel2` int(11) NOT NULL DEFAULT '0',
  `videoAverageJitter_channel2` int(11) NOT NULL DEFAULT '0',
  `videoRoundTripTime_channel2` int(11) NOT NULL DEFAULT '0',
  `videoOneWayDelay_channel2` int(11) NOT NULL DEFAULT '0',
  `videoReceptionMetrics_channel2` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoTransmissionMetrics_channel2` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=593186 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
