DROP TABLE IF EXISTS `cmr`;

CREATE TABLE `cmr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cdrRecordType` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callManagerId` int(11) NOT NULL DEFAULT '0',
  `globalCallID_callId` int(11) NOT NULL DEFAULT '0',
  `nodeId` int(11) NOT NULL DEFAULT '0',
  `directoryNum` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `callIdentifier` int(11) NOT NULL DEFAULT '0',
  `dateTimeStamp` int(11) NOT NULL DEFAULT '0',
  `numberPacketsSent` int(11) NOT NULL DEFAULT '0',
  `numberOctetsSent` int(11) NOT NULL DEFAULT '0',
  `numberPacketsReceived` int(11) NOT NULL DEFAULT '0',
  `numberOctetsReceived` int(11) NOT NULL DEFAULT '0',
  `numberPacketsLost` int(11) NOT NULL DEFAULT '0',
  `jitter` int(11) NOT NULL DEFAULT '0',
  `latency` int(11) NOT NULL DEFAULT '0',
  `pkid` int(11) NOT NULL DEFAULT '0',
  `directoryNumPartition` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `globalCallId_ClusterID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `deviceName` varchar(129) COLLATE utf8_unicode_ci NOT NULL,
  `varVQMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `duration` int(11) NOT NULL DEFAULT '0',
  `videoContentType` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `videoDuration` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsSent` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsSent` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsReceived` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsReceived` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsLost` int(11) NOT NULL DEFAULT '0',
  `videoAverageJitter` int(11) NOT NULL DEFAULT '0',
  `videoRoundTripTime` int(11) NOT NULL DEFAULT '0',
  `videoOneWayDelay` int(11) NOT NULL DEFAULT '0',
  `videoReceptionMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoTransmissionMetrics` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoContentType_channel2` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `videoDuration_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsSent_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsSent_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsReceived_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoOctetsReceived_channel2` int(11) NOT NULL DEFAULT '0',
  `numberVideoPacketsLost_channel2` int(11) NOT NULL DEFAULT '0',
  `videoAverageJitter_channel2` int(11) NOT NULL DEFAULT '0',
  `videoRoundTripTime_channel2` int(11) NOT NULL DEFAULT '0',
  `videoOneWayDelay_channel2` int(11) NOT NULL DEFAULT '0',
  `videoReceptionMetrics_channel2` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  `videoTransmissionMetrics_channel2` varchar(600) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;